fac-db:
  db_name: postgres
  host: 127.0.0.1
  name: postgres
  port: 5432
  uri: ""
  username: "postgres"
  password: ""
fac-snapshot-db:
  db_name: postgres
  host: 127.0.0.1
  name: postgres
  port: 6543
  uri: ""
  username: "postgres"
  password: ""
check-counts:
  - dissemination_general
  - dissemination_federalaward
  - dissemination_finding
  - dissemination_migrationinspectionrecord
