package environments

const LOCAL = "LOCAL"
const TESTING = "TESTING"

const SANDBOX = "SANDBOX"
const DEVELOPMENT = "DEVELOPMENT"
const PREVIEW = "PREVIEW"
const STAGING = "STAGING"
const PRODUCTION = "PRODUCTION"
