# .github/workflows/release.yaml

name: Release gov.gsa.fac.cgov-util

on:
  release:
    types: [created]

permissions:
  contents: write
  packages: write

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: linux
          goarch: amd64
          goversion: "https://go.dev/dl/go1.22.0.linux-amd64.tar.gz"
          binary_name: "gov.gsa.fac.cgov-util"
          extra_files: LICENSE README.md